### ISSUE TITLE
Use Defaults From enochecker_core

### ISSUE THREAD

**Issue by domenukk** [enowars/enochecker_cli#8]
Currently, the dev defaults for values are specified at multiple places.
With https://github.com/enowars/enochecker_core/issues/15 we will have a unified place to set default values.
Enochecker_cli should use them, instead of defining own defaults.
We can probably even add descriptions of fields to core.

**Comment by ldruschk** [comment]
Since `enochecker_cli` comes with defaults and the parser from `enochecker_cli` is used directly in `enochecker` as well, we no longer have default values in multiple places and this issue is obsolete in my opinion.

**Comment by domenukk** [comment]
We still have defaults in the html files but it seems like I'm the only person valuing usable defaults, so feel free to close 🥲
